Initial clean push - Zero Touch

diff --git a/.github/workflows/1-infra-create.yml b/.github/workflows/1-infra-create.yml
--- a/.github/workflows/1-infra-create.yml
+++ b/.github/workflows/1-infra-create.yml
@@ -19,6 +19,9 @@ jobs:
           terraform_wrapper: false
       - name: Terraform Apply
         run: |
-          cd terraform
+          cd terraform || { echo "Directory 'terraform' not found"; exit 1; }
+          
+          echo "Listing files inside terraform folder:"
+          ls -F
           terraform init
           terraform apply -auto-approve
